### ISSUE TITLE
Maj Core 8.6

### ISSUE THREAD

**Issue by FlorentTorregrosa** [FlorentTorregrosa/socle-drupalcampfr#15]
Salut @kgaut,

Je peux faire la maj vers Drupal 8.6 ? ou bien as-tu attaqué le site Paris 2019 et dans ce cas il faut qu'on se coordonne pour la condifuration ?

**Comment by kgaut** [comment]
Yo, tu peux y aller je n'ai pas encore commencé

**Comment by FlorentTorregrosa** [comment]
Ok. Merci pour ton retour.
