### ISSUE TITLE
Suppression de branches post lannion2017

### ISSUE THREAD

**Issue by FlorentTorregrosa** [FlorentTorregrosa/socle-drupalcampfr#8]
Bonjour,

J'ai exporté la conf du site dans les features et créer une branche https://github.com/Drupal-FR/socle-drupalcampfr/tree/lannion2017 pour avoir l'état du site (code et conf) lors du camp.

Je vais retirer les modifications faîtes spécialement pour ce camp et mettre à jour les scripts, le core, les modules etc. pour avoir le socle de prêt pour le prochain camp sur la branche 8.x-1.x.

Est-ce que les branches 8.x-1.x_debug-integ et bzh-2017-integration peuvent être supprimées ?

**Comment by GoZOo** [comment]
Oui pour moi

Le 18 nov. 2017 18:52, "Florent Torregrosa" <notifications@github.com> a
écrit :

**Comment by FlorentTorregrosa** [comment]
Ok. Merci pour ton retour :)
